name: ToysRUs 5min Stock Monitor

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright
          playwright install chromium --with-deps

      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          # ★ ここで、隠したユーザーIDをPythonに渡します！
          DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
        run: python monitor.py
